import argparse
from os.path import join
import scanpy as sc; sc.set_figure_params(color_map="viridis", frameon=False)
import dropkick as dk
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt


parser = argparse.ArgumentParser()
parser.add_argument('--ad', dest="ad", default = None, required = True, help = 'AnnData object generated by dropkick.')
parser.add_argument('--outdir', dest="outdir", default = None, required = True, help = 'Output directory.')
args = parser.parse_args()

adfile = args.ad
outdir = args.outdir

## Testing
# adfile = "results/freeze1/dropkick/Sample_5124-NM-2-hg38/dropkick.h5ad"
# outdir = "results/freeze1/dropkick/Sample_5124-NM-2-hg38"

### Get AnnData
ad = sc.read(adfile)

# plot dropkick score distributions
score_plt = dk.score_plot(ad)
score_plt.savefig(join(outdir,"dropkick_score.png"))

coef_plt = dk.coef_plot(ad)
coef_plt.savefig(join(outdir,"dropkick_coef.png"))
